services:
  mongo:
    image: mongo:8
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--setParameter",
        "enableTestCommands=1",
      ]
    ports:
      - "27018:27017"
    healthcheck:
      test: |
        mongosh --quiet --eval "try { rs.status().ok } catch (e) { rs.initiate().ok }"
      interval: 5s
      timeout: 5s
      retries: 12
