[package]
name = "urva"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "MongoDB ODM for Rust"

[dependencies]
futures-util.workspace = true
mongodb.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { version = "1", default-features = false, features = ["time"] }
urva-derive.workspace = true

[dev-dependencies]
tokio.workspace = true
trybuild.workspace = true
